#
#spring:
#  application:
#    name: socket-server
#
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    fetch-registry: false
#    service-url:
#      default-zone: http://http://144.24.87.198:8188//eureka